apiVersion: v1
kind: Pod
metadata:
  name: vertx-http-app-failing
  labels:
    app: vertx-http-app-failing
spec:
  containers:
  - image: ppatierno/vertx-http-app-failing:latest
    imagePullPolicy: IfNotPresent
    name: vertx-http-app
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15