apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vertx-http-app
spec:
  replicas: 3
  template:
    metadata:
      name: vertx-http-app
      labels:
        app: vertx-http-app
    spec:
      containers:
      - image: ppatierno/vertx-http-app:latest
        imagePullPolicy: IfNotPresent
        name: vertx-http-app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: MY_ENV
          valueFrom:
            configMapKeyRef:
              name: vertx-http-app-cm
              key: my-env
        volumeMounts:
          - name: my-file-volume
            mountPath: /tmp/my-file.txt
            subPath: my-file.txt
      volumes:
        - name: my-file-volume
          configMap:
            name: vertx-http-app-cm