apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vertx-http-app
spec:
  replicas: 3
  template:
    metadata:
      name: vertx-http-app
      labels:
        app: vertx-http-app
    spec:
      containers:
      - image: ppatierno/vertx-http-app:v1
        imagePullPolicy: IfNotPresent
        name: vertx-http-app
        ports:
        - containerPort: 8080
          protocol: TCP
  # for slowing down the rolling update process
  # how long a newly created pod should be ready before the pod is treated as available
  minReadySeconds: 10